image: Visual Studio 2017
version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: >-
    cd src/DarkSkyCore

    dotnet restore

    dotnet build --configuration release


    cd ../../

    dotnet pack --configuration release --include-symbols -o ../../nupkgs/ src/DarkSkyCore
test_script:
- ps: >-
    cd test/DarkSkyCore.Tests

    dotnet restore

    dotnet test --filter "FullyQualifiedName~DarkSky.UnitTests"

    if (Test-Path End:\APPVEYOR_REPO_TAG) { dotnet test --filter "FullyQualifiedName~DarkSky.IntegrationTests" }
artifacts:
- path: .\nupkgs\**\*.nupkg
  name: nuget
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: YAF0FoHQVDwWAUmD/H8JUYkjiv4baMyRNdTaOgIw/NVMmo9IiYPq1wPOY525ubJG
  on:
    APPVEYOR_REPO_TAG: true
